name: Hello
version: 1.0-SNAPSHOT
main: rob.plugins.hello.Hello
api-version: 1.13
commands:
  makepool:
    description: Supposed to make a pool, currently makes a diagonal line
    usage: /<command>
  makeone:
    description: makes a tnt arch for no reason...
    usage: /<command>
